/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * This is a simple component that demonstrates how to use Stencil with Tailwind CSS.
     * @cssprop {Background} [--tw-bg-opacity=0.2] - Something that can be passed as a CSS style
     */
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    /**
     * This is a simple component that demonstrates how to use Stencil with Tailwind CSS.
     * @cssprop {Background} [--tw-bg-opacity=0.2] - Something that can be passed as a CSS style
     */
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    /**
     * This is a simple component that demonstrates how to use Stencil with Tailwind CSS.
     * @cssprop {Background} [--tw-bg-opacity=0.2] - Something that can be passed as a CSS style
     */
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * This is a simple component that demonstrates how to use Stencil with Tailwind CSS.
             * @cssprop {Background} [--tw-bg-opacity=0.2] - Something that can be passed as a CSS style
             */
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
